import{a as w,S as L,i}from"./assets/vendor-CesYmgD5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const b="https://pixabay.com/api/",S="57464539-19ea2289c3195b6eb6e9382b1";async function f(a,r=1,t=15){try{return(await w.get(b,{params:{key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t}})).data}catch(s){throw console.error("Pixabay API error:",s),s}}const m=document.querySelector(".gallery");let v=new L(".gallery a");function q(){m.innerHTML=""}function p(a){const r=a.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),v.refresh()}function g(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector(".loader").classList.add("hidden")}const P=document.querySelector(".form"),c=document.querySelector("#load-more");document.querySelector(".loader");let l="",n=1;const d=15;let y=0;P.addEventListener("submit",async a=>{if(a.preventDefault(),l=a.target.elements["search-text"].value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search term!"});return}q(),n=1,c.style.display="none",g();try{const{hits:r,totalHits:t}=await f(l,n,d);y=t,r.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(p(r),n*d<y&&(c.style.display="block"))}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{h()}});c.addEventListener("click",async()=>{n+=1,g();try{const{hits:a}=await f(l,n,d);p(a);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),n*d>=y&&(c.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{h()}});
//# sourceMappingURL=index.js.map
