import{a as b,S,i as n}from"./assets/vendor-CesYmgD5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",q="57464539-19ea2289c3195b6eb6e9382b1";async function y(a,r=1,t=15){try{return(await b.get(v,{params:{key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t}})).data}catch(s){throw console.error("Pixabay API error:",s),s}}const m=document.querySelector(".gallery");let P=new S(".gallery a");function E(){m.innerHTML=""}function h(a){const r=a.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function g(){document.querySelector(".loader").classList.remove("hidden")}function p(){document.querySelector(".loader").classList.add("hidden")}const w=document.querySelector("#load-more");function L(){w.style.display="block"}function u(){w.style.display="none"}const $=document.querySelector(".form"),I=document.querySelector("#load-more");document.querySelector(".loader");let l="",i=1;const c=15;let f=0;$.addEventListener("submit",async a=>{if(a.preventDefault(),l=a.target.elements["search-text"].value.trim(),!l){n.warning({title:"Warning",message:"Please enter a search term!"});return}E(),i=1,u(),g();try{const{hits:r,totalHits:t}=await y(l,i,c);f=t,r.length===0?n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(h(r),i*c<f?L():n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong. Try again later."})}finally{p()}});I.addEventListener("click",async()=>{i+=1,u(),g();try{const{hits:a}=await y(l,i,c);h(a);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*c<f?L():(u(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Error",message:"Something went wrong. Try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
