import{a as L,S as b,i}from"./assets/vendor-CesYmgD5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",q="57464539-19ea2289c3195b6eb6e9382b1";async function f(a,r=1,t=15){try{return(await L.get(S,{params:{key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t}})).data}catch(n){throw console.error("Pixabay API error:",n),n}}const m=document.querySelector(".gallery");let v=new b(".gallery a");function P(){m.innerHTML=""}function h(a){const r=a.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),v.refresh()}function p(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}const w=document.querySelector("#load-more");function E(){w.style.display="block"}function $(){w.style.display="none"}const M=document.querySelector(".form"),u=document.querySelector("#load-more");document.querySelector(".loader");let l="",s=1;const c=15;let y=0;M.addEventListener("submit",async a=>{if(a.preventDefault(),l=a.target.elements["search-text"].value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search term!"});return}P(),s=1,u.style.display="none",p();try{const{hits:r,totalHits:t}=await f(l,s,c);y=t,r.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(h(r),s*c<y&&(u.style.display="block"))}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{g()}});u.addEventListener("click",async()=>{s+=1,$(),p();try{const{hits:a}=await f(l,s,c);h(a);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),s*c>=y&&(E(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong. Try again later."})}finally{g()}});
//# sourceMappingURL=index.js.map
